---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "ordernotification"
    labels: 
      app: "ordernotification"
  spec: 
    selector: 
      matchLabels: 
        app: "ordernotification"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "ordernotification"
      spec: 
        containers: 
          - 
            name: "ordernotification"
            image: "ordernotification"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "ordernotification"
    labels: 
      app: "ordernotification"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "ordernotification"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "order"
    labels: 
      app: "order"
  spec: 
    selector: 
      matchLabels: 
        app: "order"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "order"
      spec: 
        containers: 
          - 
            name: "order"
            image: "order"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "order"
    labels: 
      app: "order"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "order"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "payment"
    labels: 
      app: "payment"
  spec: 
    selector: 
      matchLabels: 
        app: "payment"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "payment"
      spec: 
        containers: 
          - 
            name: "payment"
            image: "payment"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "payment"
    labels: 
      app: "payment"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "payment"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "store"
    labels: 
      app: "store"
  spec: 
    selector: 
      matchLabels: 
        app: "store"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "store"
      spec: 
        containers: 
          - 
            name: "store"
            image: "store"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "store"
    labels: 
      app: "store"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "store"
