apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderNotification
  labels:
    app: orderNotification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderNotification
  template:
    metadata:
      labels:
        app: orderNotification
    spec:
      containers:
        - name: orderNotification
          image: username/orderNotification:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
